function parseHead(headList) {
  let config = { top: 0, left: 0, right: 0, bottom: 0 };
  headList.forEach((side) => {
    config[side] = 1;
  });
  return config;
}
const RIGHT = parseHead(["right"]),
  LEFT = parseHead(["left"]),
  NONE = parseHead([]),
  LEFTRIGHT = parseHead(["left", "right"]),
  BOTTOM = parseHead(["bottom"]),
  TOP = parseHead(["top"]),
  TOPBOTTOM = parseHead(["top", "bottom"]),
  FULL = parseHead(["top", "bottom", "left", "right"]),
  TOPLEFT = parseHead(["top", "left"]),
  TOPRIGHT = parseHead(["right", "top"]),
  RIGHTBOTTOM = parseHead(["right", "bottom"]),
  TOPLEFTRIGHT = parseHead(["top", "left", "right"]),
  BOTTOMLEFT = parseHead(["bottom", "left"]),
  BOTTOMRIGHT = parseHead(["bottom", "right"]);
export const DIC_PIEZAS = {
  p1_1: RIGHT,
  p1_2: BOTTOM,
  p1_3: TOP,
  p1_4: LEFT,
  //
  p2_1: RIGHT,
  p2_2: NONE,
  p2_3: LEFT,
  p2_4: TOPBOTTOM,
  p2_5: FULL,
  p2_6: TOPBOTTOM,
  p2_7: RIGHT,
  p2_8: NONE,
  p2_9: LEFT,
  //
  p3_1: RIGHT,
  p3_2: BOTTOM,
  p3_3: LEFTRIGHT,
  p3_4: BOTTOM,
  p3_5: TOPBOTTOM,
  p3_6: BOTTOMLEFT,
  p3_7: TOPLEFT,
  p3_8: LEFT,
  p3_9: RIGHTBOTTOM,
  p3_10: RIGHTBOTTOM,
  p3_11: TOPRIGHT,
  p3_12: TOPBOTTOM,
  p3_13: RIGHT,
  p3_14: NONE,
  p3_15: TOPLEFTRIGHT,
  p3_16: NONE,
  //
  p4_1: RIGHT,
  p4_2: BOTTOM,
  p4_3: LEFTRIGHT,
  p4_4: BOTTOM,
  p4_5: LEFT,
  p4_6: TOPBOTTOM,
  p4_7: BOTTOMLEFT,
  p4_8: TOPLEFT,
  p4_9: LEFTRIGHT,
  p4_10: TOPBOTTOM,
  p4_11: RIGHTBOTTOM,
  p4_12: RIGHTBOTTOM,
  p4_13: TOPRIGHT,
  p4_14: TOPBOTTOM,
  p4_15: BOTTOMLEFT,
  p4_16: BOTTOMRIGHT,
  p4_17: BOTTOM,
  p4_18: TOPLEFTRIGHT,
  p4_19: BOTTOMRIGHT,
  p4_20: BOTTOM,
  p4_21: RIGHT,
  p4_22: NONE,
  p4_23: TOPLEFTRIGHT,
  p4_24: RIGHT,
  p4_25: NONE,
  
  //
  p5_1: RIGHT,

  p5_26: BOTTOM,
  p5_27: TOPLEFTRIGHT,
  p5_28:BOTTOMRIGHT,
  p5_29:RIGHT,
  p5_30:BOTTOM,
  p5_31:NONE,
  p5_32:LEFT,
  p5_33:TOPLEFTRIGHT,
  p5_34:NONE,
  p5_35:TOPLEFT,
  p5_36:LEFT,
};
